version: "3"

services:
  productdb:
    image: mariadb:10.10.2
    container_name: productDB
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST: localhost
      MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_PASSWORD: root!
      MYSQL_DATABASE: product
      MYSQL_USER: barbel
      MYSQL_PASSWORD: barbel!
      TZ: Asia/Seoul
    networks:
      - barbel-network
    restart: always
    volumes:
      - ./db/product/sql:/docker-entrypoint-initdb.d

  productdb_write:
    image: mariadb:10.10.2
    container_name: productDB_write
    ports:
      - "3309:3309"
    environment:
      MYSQL_HOST: localhost
      MYSQL_TCP_PORT: 3309
      MYSQL_ROOT_PASSWORD: root!
      MYSQL_DATABASE: product
      MYSQL_USER: barbel
      MYSQL_PASSWORD: barbel!
      TZ: Asia/Seoul
    networks:
      - barbel-network
    restart: always
    volumes:
      - ./db/product/sql_write:/docker-entrypoint-initdb.d

  memberdb:
    image: mariadb:10.10.2
    container_name: memberDB
    ports:
      - "3308:3308"
    volumes:
      - ./db/member/sql:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Seoul
      MYSQL_HOST: localhost
      MYSQL_TCP_PORT: 3308
      MYSQL_ROOT_PASSWORD: root!
      MYSQL_DATABASE: member
      MYSQL_USER: barbel
      MYSQL_PASSWORD: barbel!
    networks:
      - barbel-network
    restart: always

  product:
    image: bjk1649/product
    container_name: product
    ports:
      - 4002:4002
    networks:
      - barbel-network
    depends_on:
      - productdb
    restart: always
    tty: true
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2048M

  member:
    image: bjk1649/member
    container_name: member
    ports:
      - 4001:4001
    networks:
      - barbel-network
    depends_on:
      - memberdb
    restart: always
    tty: true
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2048M

  gateway:
    image: bjk1649/gateway
    container_name: gateway
    ports:
      - 8080:8080
    networks:
      - barbel-network
    depends_on:
      - memberdb
    restart: always
    tty: true
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2048M

  healthcheck:
    image: bjk1649/healthcheck
    container_name: healthcheck
    ports:
      - 4000:4000
    networks:
      - barbel-network
    depends_on:
      - gateway
    restart: always
    volumes:
      - /usr/local:/tmp

networks:
  barbel-network:
